sudo: required

language: java
jdk:
 - openjdk8
 
before_install:
  - chmod +x mvnw
  
script: ./mvnw clean install 

 
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-east-2
  app: springboot-gta-gamma
  env: SpringbootGtaGamma-env
  zip_file: 'target/springboot-gta-gamma-0.0.1-SNAPSHOT.jar'
  bucket_name: elasticbeanstalk-us-east-2-693831461729
  bucket_path: springboot-gta-gamma
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
